[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "parametrize_from_file"
author = "Kale Kundert"
author-email = "kale@thekunderts.net"
home-page = 'https://github.com/kalekundert/parametrize_from_file'
description-file = 'README.rst'
requires-python = "~=3.6"
requires = [
]
classifiers = [
  'Programming Language :: Python :: 3',
  'License :: OSI Approved :: MIT License',
]

[tool.flit.metadata.requires-extra]
tests = [
  'pytest',
  'pytest-cov',
  'coveralls',
]
docs = [
  'sphinx',
  'sphinx_rtd_theme',
  'autoclasstoc',
]

[tool.flit.metadata.urls]
'Documentation' = 'https://parametrize_from_file.readthedocs.io/en/latest/'
'Version Control' = 'https://github.com/kalekundert/parametrize_from_file'
'Bug Tracker' = 'https://github.com/kalekundert/parametrize_from_file/issues'
'Continuous Integration' = 'https://github.com/kalekundert/parametrize_from_file/actions'
'Test Coverage' = 'https://coveralls.io/github/kalekundert/parametrize_from_file'

[tool.semantic_release]
version_variable = 'parametrize_from_file/__init__.py:__version__'
build_command = 'python -m pip install flit && flit build'
