name: Test

on:
  push:
  pull_request:

jobs:

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install ruff
      - run: ruff check --format=github .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.x']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -e '.[test]'
      - name: Run test suite
        run: |
          pytest --cov parametrize_from_file
          docs/test_docs.sh
      - name: Report test coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          coveralls
